#!/bin/bash
{% include 'common/note.cmake' %}


CURRENT_DIR=$(cd $(dirname $0); pwd)
# echo $CURRENT_DIR
shopt -s expand_aliases
source $CURRENT_DIR/../../roslite_cli.sh
rosl_cd


PIDS=

taskset -c 1 ./ros_bridge &
PIDS="${PIDS} $!"

taskset -c 2 ./ros_param_bridge &
PIDS="${PIDS} $!"

{% for cluster in cluster_list: %}
{% if cluster in cluster_cpu_map: %}
taskset -c {{ cluster_cpu_map[cluster]|join(",") }} ./cluster-{{ cluster }} &
PIDS="${PIDS} $!"
{% else %}
./cluster-{{ cluster }} &
PIDS="${PIDS} $!"
{% endif %}

{% endfor %}

wait $PIDS
